### ISSUE TITLE
Blocked at my school.

### ISSUE THREAD

**Issue by CookieRabbit** [Browncha023/CutTheRopeHTML5#1]
It's blocked through my school district. I think they use OpenDNS if that helps.

**Comment by Browncha023** [comment]
The live demo for this project was part of EIC, which is no longer supported. I would suggest forking it with replit, netlify, heroku, or github pages depending on what your district hasn't blocked.

**Comment by CookieRabbit** [comment]
Thank you. I just looked up a tutorial for forking, I was quite confused.
